"use client";

/**
 * Triggers the service worker to pre-fetch and cache every product,
 * blog post, and policy page so the whole storefront is browsable
 * offline after the customer's first visit — not just pages they
 * happened to click on.
 *
 * Source of the URL list: /sitemap.xml (already generated by
 * app/sitemap.ts), so there's no need to duplicate the list of every
 * product/blog slug — we reuse what SEO already produces.
 */

const WARM_VERSION_KEY = "tt_cache_warmed_v1";

function isOffline() {
  return typeof navigator !== "undefined" && navigator.onLine === false;
}

async function getUrlsToWarm(): Promise<string[]> {
  const res = await fetch("/sitemap.xml", { cache: "no-store" });
  if (!res.ok) return [];
  const xml = await res.text();

  const locs = Array.from(xml.matchAll(/<loc>(.*?)<\/loc>/g)).map((m) => m[1]);

  return locs
    .map((loc) => {
      try {
        return new URL(loc).pathname;
      } catch {
        return null;
      }
    })
    .filter((p): p is string => !!p)
    .filter(
      (p) =>
        p.startsWith("/products/") ||
        p.startsWith("/blog/") ||
        p === "/privacy-policy" ||
        p === "/terms" ||
        p === "/shipping-returns" ||
        p.startsWith("/help/") ||
        p === "/blog" ||
        p === "/products"
    );
}

export async function warmFullSiteCache() {
  if (typeof window === "undefined") return;
  if (isOffline()) return;
  if (!("serviceWorker" in navigator)) return;

  // Only re-warm once per deploy — bump WARM_VERSION_KEY's suffix
  // when you want to force a re-warm for all returning visitors.
  if (localStorage.getItem(WARM_VERSION_KEY) === "done") return;

  const registration = await navigator.serviceWorker.ready;
  const controller = registration.active;
  if (!controller) return;

  const urls = await getUrlsToWarm();
  if (urls.length === 0) return;

  controller.postMessage({ type: "WARM_CACHE", urls });
  localStorage.setItem(WARM_VERSION_KEY, "done");
}