const STORAGE_KEY = "tiny_tots_pending_sales";

export function getQueuedSales() {
  const data = localStorage.getItem(STORAGE_KEY);
  if (!data) return [];
  try {
    return JSON.parse(data);
  } catch {
    return [];
  }
}

function saveQueue(queue) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(queue));
}

// clientSaleId is generated by the caller BEFORE the first network attempt,
// and reused on every retry — this is what lets the server recognize
// "same sale, being retried" instead of creating a duplicate.
export function queueSale(sale, clientSaleId) {
  const queue = getQueuedSales();
  queue.push({
    client_sale_id: clientSaleId,
    created_at: new Date().toISOString(),
    status: "pending", // "pending" | "failed"
    failReason: null,
    ...sale,
  });
  saveQueue(queue);
}

export function removeQueuedSale(clientSaleId) {
  saveQueue(getQueuedSales().filter((s) => s.client_sale_id !== clientSaleId));
}

export function markSaleFailed(clientSaleId, reason) {
  const queue = getQueuedSales().map((s) =>
    s.client_sale_id === clientSaleId ? { ...s, status: "failed", failReason: reason } : s
  );
  saveQueue(queue);
}

export function retrySale(clientSaleId) {
  const queue = getQueuedSales().map((s) =>
    s.client_sale_id === clientSaleId ? { ...s, status: "pending", failReason: null } : s
  );
  saveQueue(queue);
}

export function clearQueue() {
  localStorage.removeItem(STORAGE_KEY);
}

export async function syncQueuedSales() {
  const queue = getQueuedSales().filter((s) => s.status === "pending");
  if (queue.length === 0) return;

  console.log(`Syncing ${queue.length} pending sale(s)...`);

  for (const sale of queue) {
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 10000); // don't hang forever on a half-dead connection

      const response = await fetch("http://localhost:3000/api/checkout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: controller.signal,
        body: JSON.stringify({
          client_sale_id: sale.client_sale_id,
          cart: sale.cart,
          subtotal: sale.subtotal,
          discount: sale.discount ?? 0,
          tax: sale.tax,
          total: sale.total,
          cashier: sale.cashier,
          paymentMethod: sale.paymentMethod,
          notes: sale.notes,
        }),
      });
      clearTimeout(timeout);

      const result = await response.json();

      if (!result.success) {
        // A real server-side rejection (e.g. sold out while offline) —
        // stop retrying automatically, surface it for a human to resolve.
        markSaleFailed(sale.client_sale_id, result.message || result.error || "Rejected by server.");
        continue;
      }

      removeQueuedSale(sale.client_sale_id);
      console.log("Synced sale:", result.receipt_number, result.deduped ? "(deduped)" : "");
    } catch (error) {
      // Network-level failure (offline again, timeout, etc.) — leave as
      // "pending" and stop this pass; order is preserved for next attempt.
      console.error("Sync stopped:", error);
      break;
    }
  }

  console.log("Sync finished.");
}

export function getQueueCount() {
  return getQueuedSales().filter((s) => s.status === "pending").length;
}

export function getFailedSales() {
  return getQueuedSales().filter((s) => s.status === "failed");
}