-- ============ CUSTOMERS ============
CREATE TABLE public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id uuid REFERENCES auth.users(id),
    full_name text,
    phone text,
    email text,
    orders_count integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.customers ADD CONSTRAINT customers_phone_key UNIQUE (phone);
ALTER TABLE public.customers ADD CONSTRAINT customers_email_key UNIQUE (email);
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- ============ ORDERS ============
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number text NOT NULL,
    customer_id bigint REFERENCES public.customers(id),
    guest_name text,
    guest_phone text,
    shipping_address text NOT NULL,
    shipping_city text NOT NULL,
    status text NOT NULL DEFAULT 'new',
    payment_method text NOT NULL,
    cod_tier text,
    cod_token_amount numeric(10,2) DEFAULT 0,
    cod_token_paid boolean NOT NULL DEFAULT false,
    subtotal numeric(10,2) NOT NULL,
    delivery_fee numeric(10,2) NOT NULL DEFAULT 0,
    discount_total numeric(10,2) NOT NULL DEFAULT 0,
    total numeric(10,2) NOT NULL,
    coupon_code text REFERENCES public.coupons(code),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.orders ADD CONSTRAINT orders_order_number_key UNIQUE (order_number);
ALTER TABLE public.orders ADD CONSTRAINT orders_status_check
    CHECK (status = ANY (ARRAY['new'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text]));
ALTER TABLE public.orders ADD CONSTRAINT orders_payment_method_check
    CHECK (payment_method = ANY (ARRAY['jazzcash'::text, 'easypaisa'::text, 'card'::text, 'cod'::text]));
ALTER TABLE public.orders ADD CONSTRAINT orders_cod_tier_check
    CHECK (cod_tier = ANY (ARRAY['none'::text, 'full_cod'::text, 'token_percent'::text, 'token_flat'::text]));
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- ============ ORDER ITEMS ============
CREATE TABLE public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id),
    variant_id bigint NOT NULL REFERENCES public.variants(id),
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    line_total numeric(10,2) NOT NULL,
    unit_cost_price numeric(10,2),
    line_gross_profit numeric(10,2)
);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_quantity_check CHECK (quantity > 0);
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;