-- tinytots-web/web/supabase/migrations/20260723_product_images.sql
-- Adds multi-image support per product (primary image + gallery), backed by
-- Supabase Storage. products.image_url is kept in sync automatically so any
-- existing code that reads image_url (storefront PDP, POS, product cards)
-- keeps working without changes.

CREATE TABLE public.product_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    storage_path text NOT NULL,          -- path inside the 'product-images' bucket
    is_primary boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX idx_product_images_product_id ON public.product_images (product_id);

ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;

-- Public can view images (storefront + POS need this to render pictures)
CREATE POLICY "Public can view product images" ON public.product_images
FOR SELECT USING (true);

-- Only service_role (admin API routes) may insert/update/delete — matches
-- the existing pattern where all writes go through supabaseAdmin, never anon.
-- (No policy for INSERT/UPDATE/DELETE means only service_role, which bypasses
-- RLS entirely, can perform them — anon/authenticated are blocked by default.)

-- Enforce only one primary image per product at the database level, so a
-- buggy client can never end up with two "is_primary = true" rows.
CREATE UNIQUE INDEX idx_product_images_one_primary
ON public.product_images (product_id)
WHERE is_primary = true;

-- NOTE: products.image_url is kept in sync at the APPLICATION layer (in the
-- /api/admin/products/[id]/images route), not via a DB trigger. A trigger
-- would need to know the Supabase project's public storage URL to build a
-- full image_url, and hardcoding that into SQL is fragile across environments
-- (local/staging/prod). The API route already has this URL available after
-- every upload/delete/set-primary call, so it writes products.image_url
-- directly in the same request — simpler and environment-safe.